### Credit:
This is a practice based on the courses of "dataschool.io"
All datasets downloaded from "dataschool.io"

In [94]:
import pandas as pd

In [95]:
path = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/sms.tsv"
sms = pd.read_table(path, header = None, names = ["label", "message"])

In [96]:
sms

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [97]:
sms.shape

(5572, 2)

In [98]:
sms.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   label    5572 non-null   object
 1   message  5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [99]:
sms.describe()

label                 message
count   5572                    5572
unique     2                    5169
top      ham  Sorry, I'll call later
freq    4825                      30

In [100]:
#Create labels in a new column based of entries of other column
sms["label_num"] = sms["label"].map({
    "ham": 0,
    "spam": 1
})
sms

label                                            message  label_num
0      ham  Go until jurong point, crazy.. Available only ...          0
1      ham                      Ok lar... Joking wif u oni...          0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...          1
3      ham  U dun say so early hor... U c already then say...          0
4      ham  Nah I don't think he goes to usf, he lives aro...          0
...    ...                                                ...        ...
5567  spam  This is the 2nd time we have tried 2 contact u...          1
5568   ham               Will ü b going to esplanade fr home?          0
5569   ham  Pity, * was in mood for that. So...any other s...          0
5570   ham  The guy did some bitching but I acted like i'd...          0
5571   ham                         Rofl. Its true to its name          0

[5572 rows x 3 columns]

In [101]:
X = sms["message"]
y = sms["label_num"]
print(X.shape)
print(y.shape)

(5572,)
(5572,)


In [102]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

In [103]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state = 40
)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(4179,)
(4179,)
(1393,)
(1393,)


In [104]:
vect = CountVectorizer()
X_train_dtm = vect.fit_transform(X_train)
X_train_dtm

<4179x7494 sparse matrix of type '<class 'numpy.int64'>'
	with 55727 stored elements in Compressed Sparse Row format>

In [105]:
X_test_dtm = vect.transform(X_test)
X_test_dtm

<1393x7494 sparse matrix of type '<class 'numpy.int64'>'
	with 17116 stored elements in Compressed Sparse Row format>

In [106]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
nb = MultinomialNB()
nb.fit(X_train_dtm, y_train)

MultinomialNB()

In [107]:
y_pred_class = nb.predict(X_test_dtm)

In [108]:
accuracy_score(y_test, y_pred_class)

0.9820531227566404

In [109]:
X_train_tokens = vect.get_feature_names()
X_train_tokens

['00',
 '000',
 '000pes',
 '008704050406',
 '0089',
 '0121',
 '02',
 '0207',
 '02072069400',
 '02073162414',
 '02085076972',
 '021',
 '03',
 '04',
 '0430',
 '05',
 '050703',
 '0578',
 '06',
 '07',
 '07046744435',
 '07090201529',
 '07090298926',
 '07099833605',
 '07123456789',
 '07732584351',
 '07734396839',
 '07742676969',
 '07753741225',
 '0776xxxxxxx',
 '07781482378',
 '07786200117',
 '077xxx',
 '07801543489',
 '07808',
 '07808726822',
 '07821230901',
 '078498',
 '07880867867',
 '0789xxxxxxx',
 '07946746291',
 '0796xxxxxx',
 '07973788240',
 '07xxxxxxxxx',
 '08',
 '0800',
 '08000407165',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '08006344447',
 '0808',
 '08081263000',
 '08081560665',
 '0825',
 '083',
 '0844',
 '08448350055',
 '08448714184',
 '0845',
 '08452810071',
 '08452810073',
 '08452810075over18',
 '0870',
 '08701213186',
 '08701417012',
 '08701417012150p',
 '0870141701216',
 '087016248',
 '087

In [110]:
nb.feature_count_

array([[ 0.,  0.,  1., ...,  1.,  0.,  1.],
       [ 8., 27.,  0., ...,  0.,  1.,  0.]])

In [111]:
ham_token_count = nb.feature_count_[0, :]
ham_token_count

array([0., 0., 1., ..., 1., 0., 1.])

In [112]:
spam_token_count = nb.feature_count_[1, :]
spam_token_count

array([ 8., 27.,  0., ...,  0.,  1.,  0.])

In [113]:
tokens = pd.DataFrame({
    "tokens": X_train_tokens,
    "ham": ham_token_count,
    "spam": spam_token_count
}).set_index("tokens")
tokens

ham  spam
tokens                 
00            0.0   8.0
000           0.0  27.0
000pes        1.0   0.0
008704050406  0.0   2.0
0089          0.0   1.0
...           ...   ...
zouk          0.0   1.0
zyada         1.0   0.0
èn            1.0   0.0
ú1            0.0   1.0
〨ud           1.0   0.0

[7494 rows x 2 columns]

In [114]:
tokens.sample(5, random_state = 6)

ham  spam
tokens              
wedlunch   1.0   0.0
returns    3.0   0.0
x49        0.0   2.0
incorrect  0.0   1.0
les        1.0   0.0

In [115]:
tokens["ham"] = tokens["ham"] + 1
tokens["spam"] = tokens["spam"] + 1
tokens.sample(5, random_state = 6)

ham  spam
tokens              
wedlunch   2.0   1.0
returns    4.0   1.0
x49        1.0   3.0
incorrect  1.0   2.0
les        2.0   1.0

In [116]:
nb.class_count_

array([3612.,  567.])

In [117]:
#Null accuracy
print(nb.class_count_[0] / (nb.class_count_[0] + nb.class_count_[1]))

0.864321608040201


In [118]:
tokens["ham"] = tokens["ham"] / nb.class_count_[0]
tokens["spam"] = tokens["spam"] / nb.class_count_[0]
tokens.sample(5, random_state = 6)

ham      spam
tokens                       
wedlunch   0.000554  0.000277
returns    0.001107  0.000277
x49        0.000277  0.000831
incorrect  0.000277  0.000554
les        0.000554  0.000277

In [ ]:
tokens["spam ratio"] = tokens[]