TODO:
    - Compare Simple and StartifiedKFold
    - Nested Cross Validation

In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import cross_val_score

In [2]:
breast_cancer_orginal = load_breast_cancer()
breast_cancer_orginal.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [3]:
pd.DataFrame(breast_cancer_orginal.data)

0      1       2       3        4        5        6        7       8   \
0    17.99  10.38  122.80  1001.0  0.11840  0.27760  0.30010  0.14710  0.2419   
1    20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690  0.07017  0.1812   
2    19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740  0.12790  0.2069   
3    11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140  0.10520  0.2597   
4    20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800  0.10430  0.1809   
..     ...    ...     ...     ...      ...      ...      ...      ...     ...   
564  21.56  22.39  142.00  1479.0  0.11100  0.11590  0.24390  0.13890  0.1726   
565  20.13  28.25  131.20  1261.0  0.09780  0.10340  0.14400  0.09791  0.1752   
566  16.60  28.08  108.30   858.1  0.08455  0.10230  0.09251  0.05302  0.1590   
567  20.60  29.33  140.10  1265.0  0.11780  0.27700  0.35140  0.15200  0.2397   
568   7.76  24.54   47.92   181.0  0.05263  0.04362  0.00000  0.00000  0.1587   

          9   ...      20     21      22      23       24       25      26  \
0    0.07871  ...  25.380  17.33  184.60  2019.0  0.16220  0.66560  0.7119   
1    0.05667  ...  24.990  23.41  158.80  1956.0  0.12380  0.18660  0.2416   
2    0.05999  ...  23.570  25.53  152.50  1709.0  0.14440  0.42450  0.4504   
3    0.09744  ...  14.910  26.50   98.87   567.7  0.20980  0.86630  0.6869   
4    0.05883  ...  22.540  16.67  152.20  1575.0  0.13740  0.20500  0.4000   
..       ...  ...     ...    ...     ...     ...      ...      ...     ...   
564  0.05623  ...  25.450  26.40  166.10  2027.0  0.14100  0.21130  0.4107   
565  0.05533  ...  23.690  38.25  155.00  1731.0  0.11660  0.19220  0.3215   
566  0.05648  ...  18.980  34.12  126.70  1124.0  0.11390  0.30940  0.3403   
567  0.07016  ...  25.740  39.42  184.60  1821.0  0.16500  0.86810  0.9387   
568  0.05884  ...   9.456  30.37   59.16   268.6  0.08996  0.06444  0.0000   

         27      28       29  
0    0.2654  0.4601  0.11890  
1    0.1860  0.2750  0.08902  
2    0.2430  0.3613  0.08758  
3    0.2575  0.6638  0.17300  
4    0.1625  0.2364  0.07678  
..      ...     ...      ...  
564  0.2216  0.2060  0.07115  
565  0.1628  0.2572  0.06637  
566  0.1418  0.2218  0.07820  
567  0.2650  0.4087  0.12400  
568  0.0000  0.2871  0.07039  

[569 rows x 30 columns]

In [4]:
breast_cancer_orginal.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [5]:
X = breast_cancer_orginal.data
y = breast_cancer_orginal.target
print(X)
print(y)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
# Splitting data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, shuffle = True)

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()

### Simple Cross Validation

Trying the simplest way for cross validation and predicting result

In [9]:
Name = "Simple Cross Validation"
numberOfFolds = 10
TrainAccuracy = cross_val_score(knn, X_train, y_train, cv = numberOfFolds, scoring = 'accuracy').mean()
TrainAccuracy

0.918695652173913

In [10]:
knn.fit(X_train, y_train)
y_pred_class = knn.predict(X_test)

In [11]:
from sklearn import metrics
TestAccuracy = metrics.accuracy_score(y_test, y_pred_class) 
print (TestAccuracy)
AccuracyDifference = TrainAccuracy - TestAccuracy
print(AccuracyDifference)

0.956140350877193
-0.03744469870327993


In [12]:
totalResult = []
totalResult.append(
    {"Name": Name,
    "TrainAccuracy": TrainAccuracy,
    "TestAccuracy": TestAccuracy,
    "AccuracyDifference": AccuracyDifference}
)
totalResult

[{'Name': 'Simple Cross Validation',
  'TrainAccuracy': 0.918695652173913,
  'TestAccuracy': 0.956140350877193,
  'AccuracyDifference': -0.03744469870327993}]

### End - Simple Cross Validation

In [13]:
# Reset variables
knn = KNeighborsClassifier()
Name = ""
TrainAccuracy = -1
TestAccuracy = -1
AccuracyDifference = -1
numberOfFolds = 10

### Simple GridSearchCV
Using GridSearchCV and predicting result

In [14]:
from sklearn.model_selection import GridSearchCV

In [15]:
k_range = list(range(1, 31))
params = {}
params['n_neighbors'] = k_range

In [16]:
grid01 = GridSearchCV(knn, params, cv = numberOfFolds, n_jobs = -1, scoring = "accuracy")
grid01.fit(X_train, y_train)

GridSearchCV(cv=10, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                         13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
                                         23, 24, 25, 26, 27, 28, 29, 30]},
             scoring='accuracy')

In [17]:
print(grid01.best_params_)
TrainAccuracy = grid01.best_score_
print(TrainAccuracy)

{'n_neighbors': 8}
0.9318357487922706


In [18]:
y_pred_class = grid01.predict(X_test)

In [19]:
TestAccuracy = metrics.accuracy_score(y_test, y_pred_class) 
print (TestAccuracy)
AccuracyDifference = TrainAccuracy - TestAccuracy
print(AccuracyDifference)

0.956140350877193
-0.024304602084922355


In [20]:
totalResult.append(
    {"Name": "Simple GridSearchCV",
    "TrainAccuracy": TrainAccuracy,
    "TestAccuracy": TestAccuracy,
    "AccuracyDifference": AccuracyDifference}
)
print(pd.DataFrame(totalResult))

                      Name  TrainAccuracy  TestAccuracy  AccuracyDifference
0  Simple Cross Validation       0.918696       0.95614           -0.037445
1      Simple GridSearchCV       0.931836       0.95614           -0.024305


In [21]:
from sklearn.model_selection import GridSearchCV
gridSearchCV01 = GridSearchCV(knn, params, cv = 10, n_jobs = -1)
cross_val_score(gridSearchCV01, X_train, y_train, cv = 10, scoring = "accuracy", n_jobs = -1).mean()

0.9208695652173914

In [22]:
gridSearchCV02 = GridSearchCV(knn, params, n_jobs = -1, cv = 10)
result = gridSearchCV02.fit(X_train, y_train)

In [23]:
result.best_params_

{'n_neighbors': 8}

In [24]:
result.best_score_

0.9318357487922706

### End - Simple GridSearchCV

In [25]:
# Reset variables
knn = KNeighborsClassifier()
Name = ""
TrainAccuracy = -1
TestAccuracy = -1
AccuracyDifference = -1
numberOfFolds = 10

### Nested Cross Validation v1

In [26]:
from sklearn.model_selection import cross_validate
gridSearchCV03 = GridSearchCV(knn, params, cv = numberOfFolds, n_jobs = -1)
#gridSearchCV03.fit(X_train, y_train)
#print(gridSearchCV03.best_score_, gridSearchCV03.best_params_)
# Explain difference between cross_val_score and cross_validate
#cross_val_score(gridSearchCV03, X_train, y_train, cv = numberOfFolds, n_jobs = -1)
nestedCrossValidation = cross_validate(
    gridSearchCV03, X_train, y_train, cv = numberOfFolds,
    scoring = 'accuracy', n_jobs = -1, return_estimator = True
)
pd.DataFrame(nestedCrossValidation)
pd.DataFrame(nestedCrossValidation).sort_values('test_score', ascending = False)

fit_time  score_time                                          estimator  \
0  2.170455    0.004616  GridSearchCV(cv=10, estimator=KNeighborsClassi...   
2  2.252765    0.004935  GridSearchCV(cv=10, estimator=KNeighborsClassi...   
5  2.168748    0.005191  GridSearchCV(cv=10, estimator=KNeighborsClassi...   
9  2.119225    0.002491  GridSearchCV(cv=10, estimator=KNeighborsClassi...   
4  2.188810    0.005052  GridSearchCV(cv=10, estimator=KNeighborsClassi...   
6  2.297840    0.004420  GridSearchCV(cv=10, estimator=KNeighborsClassi...   
1  2.182448    0.004736  GridSearchCV(cv=10, estimator=KNeighborsClassi...   
7  2.306099    0.004970  GridSearchCV(cv=10, estimator=KNeighborsClassi...   
3  2.184641    0.005161  GridSearchCV(cv=10, estimator=KNeighborsClassi...   
8  2.107600    0.003837  GridSearchCV(cv=10, estimator=KNeighborsClassi...   

   test_score  
0    0.956522  
2    0.956522  
5    0.955556  
9    0.955556  
4    0.934783  
6    0.933333  
1    0.891304  
7    0.888889  
3    0.869565  
8    0.866667

In [45]:
all_models = nestedCrossValidation['estimator']
all_test_scores = nestedCrossValidation['test_score']
bestModel = []
bestParams = []
bestScore = []
for estimator in all_models:
    bestModel.append(estimator.best_estimator_)
    bestParams.append(estimator.best_params_)
    bestScore.append(estimator.best_score_)

temp = {
    'estimator': bestModel,
    'bestParams': bestParams,
    'trainScore': bestScore,
    'testScore': all_test_scores
}
nestedCrossValidatedModels = pd.DataFrame(temp)
nestedCrossValidatedModels


estimator           bestParams  trainScore  \
0  KNeighborsClassifier(n_neighbors=10)  {'n_neighbors': 10}    0.926707   
1                KNeighborsClassifier()   {'n_neighbors': 5}    0.929146   
2   KNeighborsClassifier(n_neighbors=4)   {'n_neighbors': 4}    0.921829   
3   KNeighborsClassifier(n_neighbors=4)   {'n_neighbors': 4}    0.931585   
4   KNeighborsClassifier(n_neighbors=6)   {'n_neighbors': 6}    0.926707   
5   KNeighborsClassifier(n_neighbors=3)   {'n_neighbors': 3}    0.924390   
6   KNeighborsClassifier(n_neighbors=9)   {'n_neighbors': 9}    0.926829   
7                KNeighborsClassifier()   {'n_neighbors': 5}    0.929268   
8  KNeighborsClassifier(n_neighbors=10)  {'n_neighbors': 10}    0.931707   
9   KNeighborsClassifier(n_neighbors=8)   {'n_neighbors': 8}    0.929268   

   testScore  
0   0.956522  
1   0.891304  
2   0.956522  
3   0.869565  
4   0.934783  
5   0.955556  
6   0.933333  
7   0.888889  
8   0.866667  
9   0.955556

In [28]:
y_pred_class = gridSearchCV03.predict(X_test)
TestAccuracy = metrics.accuracy_score(y_test, y_pred_class)
AccuracyDifference = TrainAccuracy - TestAccuracy

NotFittedError: This GridSearchCV instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [ ]:
totalResult.append(
    {"Name": "Nested Cross Validation v1",
    "TrainAccuracy": TrainAccuracy,
    "TestAccuracy": TestAccuracy,
    "AccuracyDifference": AccuracyDifference}
)
print(pd.DataFrame(totalResult))